name = "sbtc-print"
main = "src/index.ts"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]
workers_dev = true

[vars]
PAYMENT_ADDRESS = "SP2QXPFF4M72QYZWXE7S5321XJDJ2DD32DGEMN5QA"
SBTC_PRICE_SATS = "100000"  # $1 worth of sBTC (~0.001 BTC at $100k)

[[kv_namespaces]]
binding = "PRINT_QUEUE"
id = "ce14257a584148109a1df0afe328436a"
